openapi: 3.0.0
info:
  title: Sample
  version: 0.0.0
tags:
  - name: Users
paths:
  /users:
    get:
      operationId: getUsers
      summary: ユーザー一覧取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      tags:
        - Users
    post:
      operationId: createUser
      summary: ユーザー作成
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
  /users/{id}:
    get:
      operationId: getUser
      summary: ユーザー取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      tags:
        - Users
    put:
      operationId: updateUser
      summary: ユーザー更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/BadRequestError'
                  - $ref: '#/components/schemas/BadRequestError'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateOrUpdate'
    delete:
      operationId: deleteUser
      summary: ユーザー削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      tags:
        - Users
components:
  schemas:
    BadRequestError:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          enum:
            - BAD_REQUEST
      allOf:
        - $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    InternalServerError:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          enum:
            - INTERNAL_SERVER_ERROR
      allOf:
        - $ref: '#/components/schemas/Error'
    NotFoundError:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          enum:
            - NOT_FOUND
      allOf:
        - $ref: '#/components/schemas/Error'
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
    UserCreate:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
    UserCreateOrUpdate:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
    UsersResponse:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
servers:
  - url: https://example.com
    description: Server endpoint
    variables: {}
