name: Generate OpenAPI Spec

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature/**
    paths:
      - model/**
      - routes/**
      - ./main.tsp

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Dependency restore
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Dependency installing
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Installing dependencies..."
          npm ci
      
      - name: Generate OpenAPI spec
        run: |
          tsp compile ./main.tsp

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code --quiet generated/openapi/api.yaml; then
            echo "No changes detected in OpenAPI specification."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in OpenAPI specification."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add generated/openapi/api.yaml
          git commit -m "chore: Update OpenAPI specification [skip ci]"
          git push

    
       